from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model


class ApiInvokerCount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_id=None, count=None):  # noqa: E501
        """ApiInvokerCount - a model defined in OpenAPI

        :param api_id: The api_id of this ApiInvokerCount.  # noqa: E501
        :type api_id: str
        :param count: The count of this ApiInvokerCount.  # noqa: E501
        :type count: int
        """
        self.openapi_types = {
            'api_id': str,
            'count': int
        }

        self.attribute_map = {
            'api_id': 'apiId',
            'count': 'count'
        }

        self._api_id = api_id
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'ApiInvokerCount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiInvokerCount of this ApiInvokerCount.  # noqa: E501
        :rtype: ApiInvokerCount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_id(self) -> str:
        """Gets the api_id of this ApiInvokerCount.


        :return: The api_id of this ApiInvokerCount.
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id: str):
        """Sets the api_id of this ApiInvokerCount.


        :param api_id: The api_id of this ApiInvokerCount.
        :type api_id: str
        """
        if api_id is None:
            raise ValueError("Invalid value for `api_id`, must not be `None`")  # noqa: E501

        self._api_id = api_id

    @property
    def count(self) -> int:
        """Gets the count of this ApiInvokerCount.

        Contains the number of times the API Invokers requested to onboard the service API(s) API.   # noqa: E501

        :return: The count of this ApiInvokerCount.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this ApiInvokerCount.

        Contains the number of times the API Invokers requested to onboard the service API(s) API.   # noqa: E501

        :param count: The count of this ApiInvokerCount.
        :type count: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count
