from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model


class ApiInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_name=None, supported_api_versions=None):  # noqa: E501
        """ApiInfo - a model defined in OpenAPI

        :param api_name: The api_name of this ApiInfo.  # noqa: E501
        :type api_name: str
        :param supported_api_versions: The supported_api_versions of this ApiInfo.  # noqa: E501
        :type supported_api_versions: List[str]
        """
        self.openapi_types = {
            'api_name': str,
            'supported_api_versions': List[str]
        }

        self.attribute_map = {
            'api_name': 'apiName',
            'supported_api_versions': 'supportedApiVersions'
        }

        self._api_name = api_name
        self._supported_api_versions = supported_api_versions

    @classmethod
    def from_dict(cls, dikt) -> 'ApiInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiInfo of this ApiInfo.  # noqa: E501
        :rtype: ApiInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_name(self) -> str:
        """Gets the api_name of this ApiInfo.


        :return: The api_name of this ApiInfo.
        :rtype: str
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name: str):
        """Sets the api_name of this ApiInfo.


        :param api_name: The api_name of this ApiInfo.
        :type api_name: str
        """
        if api_name is None:
            raise ValueError("Invalid value for `api_name`, must not be `None`")  # noqa: E501

        self._api_name = api_name

    @property
    def supported_api_versions(self) -> List[str]:
        """Gets the supported_api_versions of this ApiInfo.


        :return: The supported_api_versions of this ApiInfo.
        :rtype: List[str]
        """
        return self._supported_api_versions

    @supported_api_versions.setter
    def supported_api_versions(self, supported_api_versions: List[str]):
        """Sets the supported_api_versions of this ApiInfo.


        :param supported_api_versions: The supported_api_versions of this ApiInfo.
        :type supported_api_versions: List[str]
        """
        if supported_api_versions is not None and len(supported_api_versions) < 1:
            raise ValueError("Invalid value for `supported_api_versions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._supported_api_versions = supported_api_versions
