from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model


class BufferedNotificationsAction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """BufferedNotificationsAction - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'BufferedNotificationsAction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BufferedNotificationsAction of this BufferedNotificationsAction.  # noqa: E501
        :rtype: BufferedNotificationsAction
        """
        return util.deserialize_model(dikt, cls)
