from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model


class DiscoveryCount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_ids=None, discovery_req_count=None, discovery_rsp_count=None):  # noqa: E501
        """DiscoveryCount - a model defined in OpenAPI

        :param api_ids: The api_ids of this DiscoveryCount.  # noqa: E501
        :type api_ids: List[str]
        :param discovery_req_count: The discovery_req_count of this DiscoveryCount.  # noqa: E501
        :type discovery_req_count: List[int]
        :param discovery_rsp_count: The discovery_rsp_count of this DiscoveryCount.  # noqa: E501
        :type discovery_rsp_count: List[int]
        """
        self.openapi_types = {
            'api_ids': List[str],
            'discovery_req_count': List[int],
            'discovery_rsp_count': List[int]
        }

        self.attribute_map = {
            'api_ids': 'apiIds',
            'discovery_req_count': 'discoveryReqCount',
            'discovery_rsp_count': 'discoveryRspCount'
        }

        self._api_ids = api_ids
        self._discovery_req_count = discovery_req_count
        self._discovery_rsp_count = discovery_rsp_count

    @classmethod
    def from_dict(cls, dikt) -> 'DiscoveryCount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiscoveryCount of this DiscoveryCount.  # noqa: E501
        :rtype: DiscoveryCount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_ids(self) -> List[str]:
        """Gets the api_ids of this DiscoveryCount.


        :return: The api_ids of this DiscoveryCount.
        :rtype: List[str]
        """
        return self._api_ids

    @api_ids.setter
    def api_ids(self, api_ids: List[str]):
        """Sets the api_ids of this DiscoveryCount.


        :param api_ids: The api_ids of this DiscoveryCount.
        :type api_ids: List[str]
        """
        if api_ids is None:
            raise ValueError("Invalid value for `api_ids`, must not be `None`")  # noqa: E501
        if api_ids is not None and len(api_ids) < 1:
            raise ValueError("Invalid value for `api_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._api_ids = api_ids

    @property
    def discovery_req_count(self) -> List[int]:
        """Gets the discovery_req_count of this DiscoveryCount.


        :return: The discovery_req_count of this DiscoveryCount.
        :rtype: List[int]
        """
        return self._discovery_req_count

    @discovery_req_count.setter
    def discovery_req_count(self, discovery_req_count: List[int]):
        """Sets the discovery_req_count of this DiscoveryCount.


        :param discovery_req_count: The discovery_req_count of this DiscoveryCount.
        :type discovery_req_count: List[int]
        """
        if discovery_req_count is not None and len(discovery_req_count) < 1:
            raise ValueError("Invalid value for `discovery_req_count`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._discovery_req_count = discovery_req_count

    @property
    def discovery_rsp_count(self) -> List[int]:
        """Gets the discovery_rsp_count of this DiscoveryCount.


        :return: The discovery_rsp_count of this DiscoveryCount.
        :rtype: List[int]
        """
        return self._discovery_rsp_count

    @discovery_rsp_count.setter
    def discovery_rsp_count(self, discovery_rsp_count: List[int]):
        """Sets the discovery_rsp_count of this DiscoveryCount.


        :param discovery_rsp_count: The discovery_rsp_count of this DiscoveryCount.
        :type discovery_rsp_count: List[int]
        """
        if discovery_rsp_count is not None and len(discovery_rsp_count) < 1:
            raise ValueError("Invalid value for `discovery_rsp_count`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._discovery_rsp_count = discovery_rsp_count
