from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model
from capif_events.models.related_criteria import RelatedCriteria  # noqa: E501
from capif_events.models.security_method import SecurityMethod  # noqa: E501


class OnboardingCriteria(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sec_methods=None, related_criteria=None):  # noqa: E501
        """OnboardingCriteria - a model defined in OpenAPI

        :param sec_methods: The sec_methods of this OnboardingCriteria.  # noqa: E501
        :type sec_methods: List[SecurityMethod]
        :param related_criteria: The related_criteria of this OnboardingCriteria.  # noqa: E501
        :type related_criteria: RelatedCriteria
        """
        self.openapi_types = {
            'sec_methods': List[SecurityMethod],
            'related_criteria': RelatedCriteria
        }

        self.attribute_map = {
            'sec_methods': 'secMethods',
            'related_criteria': 'relatedCriteria'
        }

        self._sec_methods = sec_methods
        self._related_criteria = related_criteria

    @classmethod
    def from_dict(cls, dikt) -> 'OnboardingCriteria':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OnboardingCriteria of this OnboardingCriteria.  # noqa: E501
        :rtype: OnboardingCriteria
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sec_methods(self) -> List[SecurityMethod]:
        """Gets the sec_methods of this OnboardingCriteria.


        :return: The sec_methods of this OnboardingCriteria.
        :rtype: List[SecurityMethod]
        """
        return self._sec_methods

    @sec_methods.setter
    def sec_methods(self, sec_methods: List[SecurityMethod]):
        """Sets the sec_methods of this OnboardingCriteria.


        :param sec_methods: The sec_methods of this OnboardingCriteria.
        :type sec_methods: List[SecurityMethod]
        """
        if sec_methods is None:
            raise ValueError("Invalid value for `sec_methods`, must not be `None`")  # noqa: E501
        if sec_methods is not None and len(sec_methods) < 1:
            raise ValueError("Invalid value for `sec_methods`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._sec_methods = sec_methods

    @property
    def related_criteria(self) -> RelatedCriteria:
        """Gets the related_criteria of this OnboardingCriteria.


        :return: The related_criteria of this OnboardingCriteria.
        :rtype: RelatedCriteria
        """
        return self._related_criteria

    @related_criteria.setter
    def related_criteria(self, related_criteria: RelatedCriteria):
        """Sets the related_criteria of this OnboardingCriteria.


        :param related_criteria: The related_criteria of this OnboardingCriteria.
        :type related_criteria: RelatedCriteria
        """

        self._related_criteria = related_criteria
