from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_events import util
from capif_events.models.base_model import Model


class SupportedGADShapes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """SupportedGADShapes - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SupportedGADShapes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SupportedGADShapes of this SupportedGADShapes.  # noqa: E501
        :rtype: SupportedGADShapes
        """
        return util.deserialize_model(dikt, cls)
