from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model
from configuration.models.settings import Settings  # noqa: E501


class CapifConfiguration(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config_name=None, version=None, settings=None):  # noqa: E501
        """CapifConfiguration - a model defined in OpenAPI

        :param config_name: The config_name of this CapifConfiguration.  # noqa: E501
        :type config_name: str
        :param version: The version of this CapifConfiguration.  # noqa: E501
        :type version: str
        :param settings: The settings of this CapifConfiguration.  # noqa: E501
        :type settings: List[Settings]
        """
        self.openapi_types = {
            'config_name': str,
            'version': str,
            'settings': List[Settings]
        }

        self.attribute_map = {
            'config_name': 'config_name',
            'version': 'version',
            'settings': 'settings'
        }

        self._config_name = config_name
        self._version = version
        self._settings = settings

    @classmethod
    def from_dict(cls, dikt) -> 'CapifConfiguration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CapifConfiguration of this CapifConfiguration.  # noqa: E501
        :rtype: CapifConfiguration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config_name(self) -> str:
        """Gets the config_name of this CapifConfiguration.

        Configuration name  # noqa: E501

        :return: The config_name of this CapifConfiguration.
        :rtype: str
        """
        return self._config_name

    @config_name.setter
    def config_name(self, config_name: str):
        """Sets the config_name of this CapifConfiguration.

        Configuration name  # noqa: E501

        :param config_name: The config_name of this CapifConfiguration.
        :type config_name: str
        """

        self._config_name = config_name

    @property
    def version(self) -> str:
        """Gets the version of this CapifConfiguration.

        configuration version  # noqa: E501

        :return: The version of this CapifConfiguration.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this CapifConfiguration.

        configuration version  # noqa: E501

        :param version: The version of this CapifConfiguration.
        :type version: str
        """

        self._version = version

    @property
    def settings(self) -> List[Settings]:
        """Gets the settings of this CapifConfiguration.


        :return: The settings of this CapifConfiguration.
        :rtype: List[Settings]
        """
        return self._settings

    @settings.setter
    def settings(self, settings: List[Settings]):
        """Sets the settings of this CapifConfiguration.


        :param settings: The settings of this CapifConfiguration.
        :type settings: List[Settings]
        """

        self._settings = settings
