from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model


class ConfigCategoryCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, category_name=None, category_values=None):  # noqa: E501
        """ConfigCategoryCreateRequest - a model defined in OpenAPI

        :param category_name: The category_name of this ConfigCategoryCreateRequest.  # noqa: E501
        :type category_name: str
        :param category_values: The category_values of this ConfigCategoryCreateRequest.  # noqa: E501
        :type category_values: Dict[str, object]
        """
        self.openapi_types = {
            'category_name': str,
            'category_values': Dict[str, object]
        }

        self.attribute_map = {
            'category_name': 'category_name',
            'category_values': 'category_values'
        }

        self._category_name = category_name
        self._category_values = category_values

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigCategoryCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigCategoryCreateRequest of this ConfigCategoryCreateRequest.  # noqa: E501
        :rtype: ConfigCategoryCreateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category_name(self) -> str:
        """Gets the category_name of this ConfigCategoryCreateRequest.

        Name of the new configuration category.  # noqa: E501

        :return: The category_name of this ConfigCategoryCreateRequest.
        :rtype: str
        """
        return self._category_name

    @category_name.setter
    def category_name(self, category_name: str):
        """Sets the category_name of this ConfigCategoryCreateRequest.

        Name of the new configuration category.  # noqa: E501

        :param category_name: The category_name of this ConfigCategoryCreateRequest.
        :type category_name: str
        """
        if category_name is None:
            raise ValueError("Invalid value for `category_name`, must not be `None`")  # noqa: E501

        self._category_name = category_name

    @property
    def category_values(self) -> Dict[str, object]:
        """Gets the category_values of this ConfigCategoryCreateRequest.

        Key/value pairs that compose the new category.  # noqa: E501

        :return: The category_values of this ConfigCategoryCreateRequest.
        :rtype: Dict[str, object]
        """
        return self._category_values

    @category_values.setter
    def category_values(self, category_values: Dict[str, object]):
        """Sets the category_values of this ConfigCategoryCreateRequest.

        Key/value pairs that compose the new category.  # noqa: E501

        :param category_values: The category_values of this ConfigCategoryCreateRequest.
        :type category_values: Dict[str, object]
        """
        if category_values is None:
            raise ValueError("Invalid value for `category_values`, must not be `None`")  # noqa: E501

        self._category_values = category_values
