from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model


class GenericError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """GenericError - a model defined in OpenAPI

        :param code: The code of this GenericError.  # noqa: E501
        :type code: str
        :param message: The message of this GenericError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'GenericError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GenericError of this GenericError.  # noqa: E501
        :rtype: GenericError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this GenericError.


        :return: The code of this GenericError.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this GenericError.


        :param code: The code of this GenericError.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this GenericError.


        :return: The message of this GenericError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GenericError.


        :param message: The message of this GenericError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
