from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model
from configuration.models.settings_acl_policy_settings import \
    SettingsAclPolicySettings  # noqa: E501
from configuration.models.settings_certificates_expiry import \
    SettingsCertificatesExpiry  # noqa: E501
from configuration.models.settings_security_method_priority import \
    SettingsSecurityMethodPriority  # noqa: E501


class Settings(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, certificates_expiry=None, security_method_priority=None, acl_policy_settings=None):  # noqa: E501
        """Settings - a model defined in OpenAPI

        :param certificates_expiry: The certificates_expiry of this Settings.  # noqa: E501
        :type certificates_expiry: SettingsCertificatesExpiry
        :param security_method_priority: The security_method_priority of this Settings.  # noqa: E501
        :type security_method_priority: SettingsSecurityMethodPriority
        :param acl_policy_settings: The acl_policy_settings of this Settings.  # noqa: E501
        :type acl_policy_settings: SettingsAclPolicySettings
        """
        self.openapi_types = {
            'certificates_expiry': SettingsCertificatesExpiry,
            'security_method_priority': SettingsSecurityMethodPriority,
            'acl_policy_settings': SettingsAclPolicySettings
        }

        self.attribute_map = {
            'certificates_expiry': 'certificates_expiry',
            'security_method_priority': 'security_method_priority',
            'acl_policy_settings': 'acl_policy_settings'
        }

        self._certificates_expiry = certificates_expiry
        self._security_method_priority = security_method_priority
        self._acl_policy_settings = acl_policy_settings

    @classmethod
    def from_dict(cls, dikt) -> 'Settings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Settings of this Settings.  # noqa: E501
        :rtype: Settings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def certificates_expiry(self) -> SettingsCertificatesExpiry:
        """Gets the certificates_expiry of this Settings.


        :return: The certificates_expiry of this Settings.
        :rtype: SettingsCertificatesExpiry
        """
        return self._certificates_expiry

    @certificates_expiry.setter
    def certificates_expiry(self, certificates_expiry: SettingsCertificatesExpiry):
        """Sets the certificates_expiry of this Settings.


        :param certificates_expiry: The certificates_expiry of this Settings.
        :type certificates_expiry: SettingsCertificatesExpiry
        """

        self._certificates_expiry = certificates_expiry

    @property
    def security_method_priority(self) -> SettingsSecurityMethodPriority:
        """Gets the security_method_priority of this Settings.


        :return: The security_method_priority of this Settings.
        :rtype: SettingsSecurityMethodPriority
        """
        return self._security_method_priority

    @security_method_priority.setter
    def security_method_priority(self, security_method_priority: SettingsSecurityMethodPriority):
        """Sets the security_method_priority of this Settings.


        :param security_method_priority: The security_method_priority of this Settings.
        :type security_method_priority: SettingsSecurityMethodPriority
        """

        self._security_method_priority = security_method_priority

    @property
    def acl_policy_settings(self) -> SettingsAclPolicySettings:
        """Gets the acl_policy_settings of this Settings.


        :return: The acl_policy_settings of this Settings.
        :rtype: SettingsAclPolicySettings
        """
        return self._acl_policy_settings

    @acl_policy_settings.setter
    def acl_policy_settings(self, acl_policy_settings: SettingsAclPolicySettings):
        """Sets the acl_policy_settings of this Settings.


        :param acl_policy_settings: The acl_policy_settings of this Settings.
        :type acl_policy_settings: SettingsAclPolicySettings
        """

        self._acl_policy_settings = acl_policy_settings
