from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model


class SettingsSecurityMethodPriority(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, oauth=None, pki=None, psk=None):  # noqa: E501
        """SettingsSecurityMethodPriority - a model defined in OpenAPI

        :param oauth: The oauth of this SettingsSecurityMethodPriority.  # noqa: E501
        :type oauth: int
        :param pki: The pki of this SettingsSecurityMethodPriority.  # noqa: E501
        :type pki: int
        :param psk: The psk of this SettingsSecurityMethodPriority.  # noqa: E501
        :type psk: int
        """
        self.openapi_types = {
            'oauth': int,
            'pki': int,
            'psk': int
        }

        self.attribute_map = {
            'oauth': 'oauth',
            'pki': 'pki',
            'psk': 'psk'
        }

        self._oauth = oauth
        self._pki = pki
        self._psk = psk

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsSecurityMethodPriority':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Settings_security_method_priority of this SettingsSecurityMethodPriority.  # noqa: E501
        :rtype: SettingsSecurityMethodPriority
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oauth(self) -> int:
        """Gets the oauth of this SettingsSecurityMethodPriority.


        :return: The oauth of this SettingsSecurityMethodPriority.
        :rtype: int
        """
        return self._oauth

    @oauth.setter
    def oauth(self, oauth: int):
        """Sets the oauth of this SettingsSecurityMethodPriority.


        :param oauth: The oauth of this SettingsSecurityMethodPriority.
        :type oauth: int
        """

        self._oauth = oauth

    @property
    def pki(self) -> int:
        """Gets the pki of this SettingsSecurityMethodPriority.


        :return: The pki of this SettingsSecurityMethodPriority.
        :rtype: int
        """
        return self._pki

    @pki.setter
    def pki(self, pki: int):
        """Sets the pki of this SettingsSecurityMethodPriority.


        :param pki: The pki of this SettingsSecurityMethodPriority.
        :type pki: int
        """

        self._pki = pki

    @property
    def psk(self) -> int:
        """Gets the psk of this SettingsSecurityMethodPriority.


        :return: The psk of this SettingsSecurityMethodPriority.
        :rtype: int
        """
        return self._psk

    @psk.setter
    def psk(self, psk: int):
        """Sets the psk of this SettingsSecurityMethodPriority.


        :param psk: The psk of this SettingsSecurityMethodPriority.
        :type psk: int
        """

        self._psk = psk
