from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from configuration import util
from configuration.models.base_model import Model


class SettingsAclPolicySettings(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, allowed_total_invocations=None, allowed_invocations_per_second=None, allowed_invocations_time_range_days=None):  # noqa: E501
        """SettingsAclPolicySettings - a model defined in OpenAPI

        :param allowed_total_invocations: The allowed_total_invocations of this SettingsAclPolicySettings.  # noqa: E501
        :type allowed_total_invocations: str
        :param allowed_invocations_per_second: The allowed_invocations_per_second of this SettingsAclPolicySettings.  # noqa: E501
        :type allowed_invocations_per_second: str
        :param allowed_invocations_time_range_days: The allowed_invocations_time_range_days of this SettingsAclPolicySettings.  # noqa: E501
        :type allowed_invocations_time_range_days: int
        """
        self.openapi_types = {
            'allowed_total_invocations': str,
            'allowed_invocations_per_second': str,
            'allowed_invocations_time_range_days': int
        }

        self.attribute_map = {
            'allowed_total_invocations': 'allowed_total_invocations',
            'allowed_invocations_per_second': 'allowed_invocations_per_second',
            'allowed_invocations_time_range_days': 'allowed_invocations_time_range_days'
        }

        self._allowed_total_invocations = allowed_total_invocations
        self._allowed_invocations_per_second = allowed_invocations_per_second
        self._allowed_invocations_time_range_days = allowed_invocations_time_range_days

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsAclPolicySettings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Settings_acl_policy_settings of this SettingsAclPolicySettings.  # noqa: E501
        :rtype: SettingsAclPolicySettings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allowed_total_invocations(self) -> str:
        """Gets the allowed_total_invocations of this SettingsAclPolicySettings.

        total number of requests the invoker can make  # noqa: E501

        :return: The allowed_total_invocations of this SettingsAclPolicySettings.
        :rtype: str
        """
        return self._allowed_total_invocations

    @allowed_total_invocations.setter
    def allowed_total_invocations(self, allowed_total_invocations: str):
        """Sets the allowed_total_invocations of this SettingsAclPolicySettings.

        total number of requests the invoker can make  # noqa: E501

        :param allowed_total_invocations: The allowed_total_invocations of this SettingsAclPolicySettings.
        :type allowed_total_invocations: str
        """

        self._allowed_total_invocations = allowed_total_invocations

    @property
    def allowed_invocations_per_second(self) -> str:
        """Gets the allowed_invocations_per_second of this SettingsAclPolicySettings.

        total number of requests the invoker can make per second  # noqa: E501

        :return: The allowed_invocations_per_second of this SettingsAclPolicySettings.
        :rtype: str
        """
        return self._allowed_invocations_per_second

    @allowed_invocations_per_second.setter
    def allowed_invocations_per_second(self, allowed_invocations_per_second: str):
        """Sets the allowed_invocations_per_second of this SettingsAclPolicySettings.

        total number of requests the invoker can make per second  # noqa: E501

        :param allowed_invocations_per_second: The allowed_invocations_per_second of this SettingsAclPolicySettings.
        :type allowed_invocations_per_second: str
        """

        self._allowed_invocations_per_second = allowed_invocations_per_second

    @property
    def allowed_invocations_time_range_days(self) -> int:
        """Gets the allowed_invocations_time_range_days of this SettingsAclPolicySettings.

        time range when an invoker can make requests  # noqa: E501

        :return: The allowed_invocations_time_range_days of this SettingsAclPolicySettings.
        :rtype: int
        """
        return self._allowed_invocations_time_range_days

    @allowed_invocations_time_range_days.setter
    def allowed_invocations_time_range_days(self, allowed_invocations_time_range_days: int):
        """Sets the allowed_invocations_time_range_days of this SettingsAclPolicySettings.

        time range when an invoker can make requests  # noqa: E501

        :param allowed_invocations_time_range_days: The allowed_invocations_time_range_days of this SettingsAclPolicySettings.
        :type allowed_invocations_time_range_days: int
        """

        self._allowed_invocations_time_range_days = allowed_invocations_time_range_days
