from common.bodyRequests import *
from api_invoker_management.bodyRequests import *
from api_logging_service.bodyRequests import *
from api_publish_service.bodyRequests import *
from api_events.bodyRequests import *
from security_api.bodyRequests import *
from api_provider_management.bodyRequests import *
from vendor_extensibility.bodyRequests import *
from vault_requests.bodyRequests import *
from helper_service.bodyRequests import *
