from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api_invoker_management import util
from api_invoker_management.models.base_model import Model
from api_invoker_management.models.enrol_fail_cause import \
    EnrolFailCause  # noqa: E501


class EnrolFailReason(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_name=None, failure_code=None):  # noqa: E501
        """EnrolFailReason - a model defined in OpenAPI

        :param api_name: The api_name of this EnrolFailReason.  # noqa: E501
        :type api_name: List[str]
        :param failure_code: The failure_code of this EnrolFailReason.  # noqa: E501
        :type failure_code: EnrolFailCause
        """
        self.openapi_types = {
            'api_name': List[str],
            'failure_code': EnrolFailCause
        }

        self.attribute_map = {
            'api_name': 'apiName',
            'failure_code': 'failureCode'
        }

        self._api_name = api_name
        self._failure_code = failure_code

    @classmethod
    def from_dict(cls, dikt) -> 'EnrolFailReason':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EnrolFailReason of this EnrolFailReason.  # noqa: E501
        :rtype: EnrolFailReason
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_name(self) -> List[str]:
        """Gets the api_name of this EnrolFailReason.


        :return: The api_name of this EnrolFailReason.
        :rtype: List[str]
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name: List[str]):
        """Sets the api_name of this EnrolFailReason.


        :param api_name: The api_name of this EnrolFailReason.
        :type api_name: List[str]
        """
        if api_name is None:
            raise ValueError("Invalid value for `api_name`, must not be `None`")  # noqa: E501

        self._api_name = api_name

    @property
    def failure_code(self) -> EnrolFailCause:
        """Gets the failure_code of this EnrolFailReason.


        :return: The failure_code of this EnrolFailReason.
        :rtype: EnrolFailCause
        """
        return self._failure_code

    @failure_code.setter
    def failure_code(self, failure_code: EnrolFailCause):
        """Sets the failure_code of this EnrolFailReason.


        :param failure_code: The failure_code of this EnrolFailReason.
        :type failure_code: EnrolFailCause
        """
        if failure_code is None:
            raise ValueError("Invalid value for `failure_code`, must not be `None`")  # noqa: E501

        self._failure_code = failure_code
