from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api_invoker_management import util
from api_invoker_management.models.base_model import Model


class OnboardingFailReason(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """OnboardingFailReason - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OnboardingFailReason':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OnboardingFailReason of this OnboardingFailReason.  # noqa: E501
        :rtype: OnboardingFailReason
        """
        return util.deserialize_model(dikt, cls)
