from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api_invoker_management import util
from api_invoker_management.models.api_info import ApiInfo  # noqa: E501
from api_invoker_management.models.base_model import Model


class RelatedCriteria(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, aef_ids=None, apis=None, service_api_categories=None):  # noqa: E501
        """RelatedCriteria - a model defined in OpenAPI

        :param aef_ids: The aef_ids of this RelatedCriteria.  # noqa: E501
        :type aef_ids: List[str]
        :param apis: The apis of this RelatedCriteria.  # noqa: E501
        :type apis: List[ApiInfo]
        :param service_api_categories: The service_api_categories of this RelatedCriteria.  # noqa: E501
        :type service_api_categories: List[str]
        """
        self.openapi_types = {
            'aef_ids': List[str],
            'apis': List[ApiInfo],
            'service_api_categories': List[str]
        }

        self.attribute_map = {
            'aef_ids': 'aefIds',
            'apis': 'apis',
            'service_api_categories': 'serviceAPICategories'
        }

        self._aef_ids = aef_ids
        self._apis = apis
        self._service_api_categories = service_api_categories

    @classmethod
    def from_dict(cls, dikt) -> 'RelatedCriteria':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RelatedCriteria of this RelatedCriteria.  # noqa: E501
        :rtype: RelatedCriteria
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aef_ids(self) -> List[str]:
        """Gets the aef_ids of this RelatedCriteria.


        :return: The aef_ids of this RelatedCriteria.
        :rtype: List[str]
        """
        return self._aef_ids

    @aef_ids.setter
    def aef_ids(self, aef_ids: List[str]):
        """Sets the aef_ids of this RelatedCriteria.


        :param aef_ids: The aef_ids of this RelatedCriteria.
        :type aef_ids: List[str]
        """
        if aef_ids is not None and len(aef_ids) < 1:
            raise ValueError("Invalid value for `aef_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._aef_ids = aef_ids

    @property
    def apis(self) -> List[ApiInfo]:
        """Gets the apis of this RelatedCriteria.


        :return: The apis of this RelatedCriteria.
        :rtype: List[ApiInfo]
        """
        return self._apis

    @apis.setter
    def apis(self, apis: List[ApiInfo]):
        """Sets the apis of this RelatedCriteria.


        :param apis: The apis of this RelatedCriteria.
        :type apis: List[ApiInfo]
        """
        if apis is not None and len(apis) < 1:
            raise ValueError("Invalid value for `apis`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._apis = apis

    @property
    def service_api_categories(self) -> List[str]:
        """Gets the service_api_categories of this RelatedCriteria.


        :return: The service_api_categories of this RelatedCriteria.
        :rtype: List[str]
        """
        return self._service_api_categories

    @service_api_categories.setter
    def service_api_categories(self, service_api_categories: List[str]):
        """Sets the service_api_categories of this RelatedCriteria.


        :param service_api_categories: The service_api_categories of this RelatedCriteria.
        :type service_api_categories: List[str]
        """
        if service_api_categories is not None and len(service_api_categories) < 1:
            raise ValueError("Invalid value for `service_api_categories`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._service_api_categories = service_api_categories
