from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_routing_info import util
from capif_routing_info.models.base_model import Model


class Ipv6Addr1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """Ipv6Addr1 - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv6Addr1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv6Addr_1 of this Ipv6Addr1.  # noqa: E501
        :rtype: Ipv6Addr1
        """
        return util.deserialize_model(dikt, cls)
