from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class AefLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dc_id=None):  # noqa: E501
        """AefLocation - a model defined in OpenAPI

        :param dc_id: The dc_id of this AefLocation.  # noqa: E501
        :type dc_id: str
        """
        self.openapi_types = {
            'dc_id': str
        }

        self.attribute_map = {
            'dc_id': 'dcId'
        }

        self._dc_id = dc_id

    @classmethod
    def from_dict(cls, dikt) -> 'AefLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AefLocation of this AefLocation.  # noqa: E501
        :rtype: AefLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dc_id(self) -> str:
        """Gets the dc_id of this AefLocation.


        :return: The dc_id of this AefLocation.
        :rtype: str
        """
        return self._dc_id

    @dc_id.setter
    def dc_id(self, dc_id: str):
        """Sets the dc_id of this AefLocation.


        :param dc_id: The dc_id of this AefLocation.
        :type dc_id: str
        """

        self._dc_id = dc_id
