from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class CommunicationType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REQUEST_RESPONSE = 'REQUEST_RESPONSE'
    SUBSCRIBE_NOTIFY = 'SUBSCRIBE_NOTIFY'
    def __init__(self):  # noqa: E501
        """CommunicationType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommunicationType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunicationType of this CommunicationType.  # noqa: E501
        :rtype: CommunicationType
        """
        return util.deserialize_model(dikt, cls)
