from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class DataFormat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    JSON = 'JSON'
    XML = 'XML'
    PROTOBUF3 = 'PROTOBUF3'
    def __init__(self):  # noqa: E501
        """DataFormat - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataFormat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataFormat of this DataFormat.  # noqa: E501
        :rtype: DataFormat
        """
        return util.deserialize_model(dikt, cls)
