from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class InvokerSelector(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, invoker_onboarded_by_user=None, api_invoker_id=None):  # noqa: E501
        """InvokerSelector - a model defined in OpenAPI

        :param invoker_onboarded_by_user: The invoker_onboarded_by_user of this InvokerSelector.  # noqa: E501
        :type invoker_onboarded_by_user: list[str]
        :param api_invoker_id: The api_invoker_id of this InvokerSelector.  # noqa: E501
        :type api_invoker_id: list[str]
        """
        self.openapi_types = {
            'invoker_onboarded_by_user': list[str],
            'api_invoker_id': list[str]
        }

        self.attribute_map = {
            'invoker_onboarded_by_user': 'invokerOnboardedByUser',
            'api_invoker_id': 'apiInvokerId'
        }

        self._invoker_onboarded_by_user = invoker_onboarded_by_user
        self._api_invoker_id = api_invoker_id

    @classmethod
    def from_dict(cls, dikt) -> 'InvokerSelector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvokerSelector of this InvokerSelector.  # noqa: E501
        :rtype: InvokerSelector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoker_onboarded_by_user(self) -> list[str]:
        """Gets the invoker_onboarded_by_user of this InvokerSelector.


        :return: The invoker_onboarded_by_user of this InvokerSelector.
        :rtype: list[str]
        """
        return self._invoker_onboarded_by_user

    @invoker_onboarded_by_user.setter
    def invoker_onboarded_by_user(self, invoker_onboarded_by_user: list[str]):
        """Sets the invoker_onboarded_by_user of this InvokerSelector.


        :param invoker_onboarded_by_user: The invoker_onboarded_by_user of this InvokerSelector.
        :type invoker_onboarded_by_user: list[str]
        """
        if invoker_onboarded_by_user is not None and len(invoker_onboarded_by_user) < 0:
            raise ValueError("Invalid value for `invoker_onboarded_by_user`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._invoker_onboarded_by_user = invoker_onboarded_by_user

    @property
    def api_invoker_id(self) -> list[str]:
        """Gets the api_invoker_id of this InvokerSelector.


        :return: The api_invoker_id of this InvokerSelector.
        :rtype: list[str]
        """
        return self._api_invoker_id

    @api_invoker_id.setter
    def api_invoker_id(self, api_invoker_id: list[str]):
        """Sets the api_invoker_id of this InvokerSelector.


        :param api_invoker_id: The api_invoker_id of this InvokerSelector.
        :type api_invoker_id: list[str]
        """
        if api_invoker_id is not None and len(api_invoker_id) < 0:
            raise ValueError("Invalid value for `api_invoker_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_invoker_id = api_invoker_id
