from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class IpAddrRangeUeIpv4AddrRangesInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start=None, end=None):  # noqa: E501
        """IpAddrRangeUeIpv4AddrRangesInner - a model defined in OpenAPI

        :param start: The start of this IpAddrRangeUeIpv4AddrRangesInner.  # noqa: E501
        :type start: str
        :param end: The end of this IpAddrRangeUeIpv4AddrRangesInner.  # noqa: E501
        :type end: str
        """
        self.openapi_types = {
            'start': str,
            'end': str
        }

        self.attribute_map = {
            'start': 'start',
            'end': 'end'
        }

        self._start = start
        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'IpAddrRangeUeIpv4AddrRangesInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpAddrRange_ueIpv4AddrRanges_inner of this IpAddrRangeUeIpv4AddrRangesInner.  # noqa: E501
        :rtype: IpAddrRangeUeIpv4AddrRangesInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self) -> str:
        """Gets the start of this IpAddrRangeUeIpv4AddrRangesInner.


        :return: The start of this IpAddrRangeUeIpv4AddrRangesInner.
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start: str):
        """Sets the start of this IpAddrRangeUeIpv4AddrRangesInner.


        :param start: The start of this IpAddrRangeUeIpv4AddrRangesInner.
        :type start: str
        """

        self._start = start

    @property
    def end(self) -> str:
        """Gets the end of this IpAddrRangeUeIpv4AddrRangesInner.


        :return: The end of this IpAddrRangeUeIpv4AddrRangesInner.
        :rtype: str
        """
        return self._end

    @end.setter
    def end(self, end: str):
        """Sets the end of this IpAddrRangeUeIpv4AddrRangesInner.


        :param end: The end of this IpAddrRangeUeIpv4AddrRangesInner.
        :type end: str
        """

        self._end = end
