from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control.models.ip_addr_range_ue_ipv4_addr_ranges_inner import IpAddrRangeUeIpv4AddrRangesInner
from visibility_control import util

from visibility_control.models.ip_addr_range_ue_ipv4_addr_ranges_inner import IpAddrRangeUeIpv4AddrRangesInner  # noqa: E501

class IpAddrRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ue_ipv4_addr_ranges=None):  # noqa: E501
        """IpAddrRange - a model defined in OpenAPI

        :param ue_ipv4_addr_ranges: The ue_ipv4_addr_ranges of this IpAddrRange.  # noqa: E501
        :type ue_ipv4_addr_ranges: List[IpAddrRangeUeIpv4AddrRangesInner]
        """
        self.openapi_types = {
            'ue_ipv4_addr_ranges': List[IpAddrRangeUeIpv4AddrRangesInner]
        }

        self.attribute_map = {
            'ue_ipv4_addr_ranges': 'ueIpv4AddrRanges'
        }

        self._ue_ipv4_addr_ranges = ue_ipv4_addr_ranges

    @classmethod
    def from_dict(cls, dikt) -> 'IpAddrRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpAddrRange of this IpAddrRange.  # noqa: E501
        :rtype: IpAddrRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ue_ipv4_addr_ranges(self) -> List[IpAddrRangeUeIpv4AddrRangesInner]:
        """Gets the ue_ipv4_addr_ranges of this IpAddrRange.


        :return: The ue_ipv4_addr_ranges of this IpAddrRange.
        :rtype: List[IpAddrRangeUeIpv4AddrRangesInner]
        """
        return self._ue_ipv4_addr_ranges

    @ue_ipv4_addr_ranges.setter
    def ue_ipv4_addr_ranges(self, ue_ipv4_addr_ranges: List[IpAddrRangeUeIpv4AddrRangesInner]):
        """Sets the ue_ipv4_addr_ranges of this IpAddrRange.


        :param ue_ipv4_addr_ranges: The ue_ipv4_addr_ranges of this IpAddrRange.
        :type ue_ipv4_addr_ranges: List[IpAddrRangeUeIpv4AddrRangesInner]
        """

        self._ue_ipv4_addr_ranges = ue_ipv4_addr_ranges
