from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class OAuthGrantType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    CLIENT_CREDENTIALS = 'CLIENT_CREDENTIALS'
    AUTHORIZATION_CODE = 'AUTHORIZATION_CODE'
    AUTHORIZATION_CODE_WITH_PKCE = 'AUTHORIZATION_CODE_WITH_PKCE'
    def __init__(self):  # noqa: E501
        """OAuthGrantType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OAuthGrantType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OAuthGrantType of this OAuthGrantType.  # noqa: E501
        :rtype: OAuthGrantType
        """
        return util.deserialize_model(dikt, cls)
