from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class PatchProviderSelector(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_provider_id=None, api_name=None, api_id=None, aef_id=None):  # noqa: E501
        """PatchProviderSelector - a model defined in OpenAPI

        :param api_provider_id: The api_provider_id of this PatchProviderSelector.  # noqa: E501
        :type api_provider_id: list[str]
        :param api_name: The api_name of this PatchProviderSelector.  # noqa: E501
        :type api_name: list[str]
        :param api_id: The api_id of this PatchProviderSelector.  # noqa: E501
        :type api_id: list[str]
        :param aef_id: The aef_id of this PatchProviderSelector.  # noqa: E501
        :type aef_id: list[str]
        """
        self.openapi_types = {
            'api_provider_id': list[str],
            'api_name': list[str],
            'api_id': list[str],
            'aef_id': list[str]
        }

        self.attribute_map = {
            'api_provider_id': 'apiProviderId',
            'api_name': 'apiName',
            'api_id': 'apiId',
            'aef_id': 'aefId'
        }

        self._api_provider_id = api_provider_id
        self._api_name = api_name
        self._api_id = api_id
        self._aef_id = aef_id

    @classmethod
    def from_dict(cls, dikt) -> 'PatchProviderSelector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PatchProviderSelector of this PatchProviderSelector.  # noqa: E501
        :rtype: PatchProviderSelector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_provider_id(self) -> list[str]:
        """Gets the api_provider_id of this PatchProviderSelector.


        :return: The api_provider_id of this PatchProviderSelector.
        :rtype: list[str]
        """
        return self._api_provider_id

    @api_provider_id.setter
    def api_provider_id(self, api_provider_id: list[str]):
        """Sets the api_provider_id of this PatchProviderSelector.


        :param api_provider_id: The api_provider_id of this PatchProviderSelector.
        :type api_provider_id: list[str]
        """
        if api_provider_id is not None and len(api_provider_id) < 0:
            raise ValueError("Invalid value for `api_provider_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_provider_id = api_provider_id

    @property
    def api_name(self) -> list[str]:
        """Gets the api_name of this PatchProviderSelector.


        :return: The api_name of this PatchProviderSelector.
        :rtype: list[str]
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name: list[str]):
        """Sets the api_name of this PatchProviderSelector.


        :param api_name: The api_name of this PatchProviderSelector.
        :type api_name: list[str]
        """
        if api_name is not None and len(api_name) < 0:
            raise ValueError("Invalid value for `api_name`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_name = api_name

    @property
    def api_id(self) -> list[str]:
        """Gets the api_id of this PatchProviderSelector.


        :return: The api_id of this PatchProviderSelector.
        :rtype: list[str]
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id: list[str]):
        """Sets the api_id of this PatchProviderSelector.


        :param api_id: The api_id of this PatchProviderSelector.
        :type api_id: list[str]
        """
        if api_id is not None and len(api_id) < 0:
            raise ValueError("Invalid value for `api_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_id = api_id

    @property
    def aef_id(self) -> list[str]:
        """Gets the aef_id of this PatchProviderSelector.


        :return: The aef_id of this PatchProviderSelector.
        :rtype: list[str]
        """
        return self._aef_id

    @aef_id.setter
    def aef_id(self, aef_id: list[str]):
        """Sets the aef_id of this PatchProviderSelector.


        :param aef_id: The aef_id of this PatchProviderSelector.
        :type aef_id: list[str]
        """
        if aef_id is not None and len(aef_id) < 0:
            raise ValueError("Invalid value for `aef_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._aef_id = aef_id
