from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class Protocol(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    HTTP_1_1 = 'HTTP_1_1'
    HTTP_2 = 'HTTP_2'
    MQTT = 'MQTT'
    WEBSOCKET = 'WEBSOCKET'
    def __init__(self):  # noqa: E501
        """Protocol - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Protocol':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Protocol of this Protocol.  # noqa: E501
        :rtype: Protocol
        """
        return util.deserialize_model(dikt, cls)
