from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control import util


class ProviderSelector(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_by_user=None, api_provider_id=None, api_name=None, api_id=None, aef_id=None):  # noqa: E501
        """ProviderSelector - a model defined in OpenAPI

        :param created_by_user: The created_by_user of this ProviderSelector.  # noqa: E501
        :type created_by_user: str
        :param api_provider_id: The api_provider_id of this ProviderSelector.  # noqa: E501
        :type api_provider_id: list[str]
        :param api_name: The api_name of this ProviderSelector.  # noqa: E501
        :type api_name: list[str]
        :param api_id: The api_id of this ProviderSelector.  # noqa: E501
        :type api_id: list[str]
        :param aef_id: The aef_id of this ProviderSelector.  # noqa: E501
        :type aef_id: list[str]
        """
        self.openapi_types = {
            'created_by_user': str,
            'api_provider_id': list[str],
            'api_name': list[str],
            'api_id': list[str],
            'aef_id': list[str]
        }

        self.attribute_map = {
            'created_by_user': 'createdByUser',
            'api_provider_id': 'apiProviderId',
            'api_name': 'apiName',
            'api_id': 'apiId',
            'aef_id': 'aefId'
        }

        self._created_by_user = created_by_user
        self._api_provider_id = api_provider_id
        self._api_name = api_name
        self._api_id = api_id
        self._aef_id = aef_id

    @classmethod
    def from_dict(cls, dikt) -> 'ProviderSelector':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProviderSelector of this ProviderSelector.  # noqa: E501
        :rtype: ProviderSelector
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_by_user(self) -> str:
        """Gets the created_by_user of this ProviderSelector.


        :return: The created_by_user of this ProviderSelector.
        :rtype: str
        """
        return self._created_by_user

    @created_by_user.setter
    def created_by_user(self, created_by_user: str):
        """Sets the created_by_user of this ProviderSelector.


        :param created_by_user: The created_by_user of this ProviderSelector.
        :type created_by_user: str
        """
        if created_by_user is None:
            raise ValueError("Invalid value for `created_by_user`, must not be `None`")  # noqa: E501
        if created_by_user is not None and len(created_by_user) < 1:
            raise ValueError("Invalid value for `created_by_user`, length must be greater than or equal to `1`")  # noqa: E501

        self._created_by_user = created_by_user

    @property
    def api_provider_id(self) -> list[str]:
        """Gets the api_provider_id of this ProviderSelector.


        :return: The api_provider_id of this ProviderSelector.
        :rtype: list[str]
        """
        return self._api_provider_id

    @api_provider_id.setter
    def api_provider_id(self, api_provider_id: list[str]):
        """Sets the api_provider_id of this ProviderSelector.


        :param api_provider_id: The api_provider_id of this ProviderSelector.
        :type api_provider_id: list[str]
        """
        if api_provider_id is not None and len(api_provider_id) < 0:
            raise ValueError("Invalid value for `api_provider_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_provider_id = api_provider_id

    @property
    def api_name(self) -> list[str]:
        """Gets the api_name of this ProviderSelector.


        :return: The api_name of this ProviderSelector.
        :rtype: list[str]
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name: list[str]):
        """Sets the api_name of this ProviderSelector.


        :param api_name: The api_name of this ProviderSelector.
        :type api_name: list[str]
        """
        if api_name is not None and len(api_name) < 0:
            raise ValueError("Invalid value for `api_name`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_name = api_name

    @property
    def api_id(self) -> list[str]:
        """Gets the api_id of this ProviderSelector.


        :return: The api_id of this ProviderSelector.
        :rtype: list[str]
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id: list[str]):
        """Sets the api_id of this ProviderSelector.


        :param api_id: The api_id of this ProviderSelector.
        :type api_id: list[str]
        """
        if api_id is not None and len(api_id) < 0:
            raise ValueError("Invalid value for `api_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_id = api_id

    @property
    def aef_id(self) -> list[str]:
        """Gets the aef_id of this ProviderSelector.


        :return: The aef_id of this ProviderSelector.
        :rtype: list[str]
        """
        return self._aef_id

    @aef_id.setter
    def aef_id(self, aef_id: list[str]):
        """Sets the aef_id of this ProviderSelector.


        :param aef_id: The aef_id of this ProviderSelector.
        :type aef_id: list[str]
        """
        if aef_id is not None and len(aef_id) < 0:
            raise ValueError("Invalid value for `aef_id`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._aef_id = aef_id
