from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control.models.rule import Rule
from visibility_control import util

from visibility_control.models.rule import Rule  # noqa: E501

class RulesGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None, next_page_token=None):  # noqa: E501
        """RulesGet200Response - a model defined in OpenAPI

        :param items: The items of this RulesGet200Response.  # noqa: E501
        :type items: List[Rule]
        :param next_page_token: The next_page_token of this RulesGet200Response.  # noqa: E501
        :type next_page_token: str
        """
        self.openapi_types = {
            'items': List[Rule],
            'next_page_token': str
        }

        self.attribute_map = {
            'items': 'items',
            'next_page_token': 'nextPageToken'
        }

        self._items = items
        self._next_page_token = next_page_token

    @classmethod
    def from_dict(cls, dikt) -> 'RulesGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _rules_get_200_response of this RulesGet200Response.  # noqa: E501
        :rtype: RulesGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Rule]:
        """Gets the items of this RulesGet200Response.


        :return: The items of this RulesGet200Response.
        :rtype: List[Rule]
        """
        return self._items

    @items.setter
    def items(self, items: List[Rule]):
        """Sets the items of this RulesGet200Response.


        :param items: The items of this RulesGet200Response.
        :type items: List[Rule]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def next_page_token(self) -> str:
        """Gets the next_page_token of this RulesGet200Response.


        :return: The next_page_token of this RulesGet200Response.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token: str):
        """Sets the next_page_token of this RulesGet200Response.


        :param next_page_token: The next_page_token of this RulesGet200Response.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token
