from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control.models.invoker_selector import InvokerSelector
from visibility_control.models.patch_provider_selector import PatchProviderSelector
from visibility_control import util

from visibility_control.models.invoker_selector import InvokerSelector  # noqa: E501
from visibility_control.models.patch_provider_selector import PatchProviderSelector  # noqa: E501

class RulePatchRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, provider_selector=None, invoker_exceptions=None, default_access=None, enabled=None, starts_at=None, ends_at=None, notes=None):  # noqa: E501
        """RulePatchRequest - a model defined in OpenAPI

        :param provider_selector: The provider_selector of this RulePatchRequest.  # noqa: E501
        :type provider_selector: PatchProviderSelector
        :param invoker_exceptions: The invoker_exceptions of this RulePatchRequest.  # noqa: E501
        :type invoker_exceptions: InvokerSelector
        :param default_access: The default_access of this RulePatchRequest.  # noqa: E501
        :type default_access: str
        :param enabled: The enabled of this RulePatchRequest.  # noqa: E501
        :type enabled: bool
        :param starts_at: The starts_at of this RulePatchRequest.  # noqa: E501
        :type starts_at: datetime
        :param ends_at: The ends_at of this RulePatchRequest.  # noqa: E501
        :type ends_at: datetime
        :param notes: The notes of this RulePatchRequest.  # noqa: E501
        :type notes: str
        """
        self.openapi_types = {
            'provider_selector': PatchProviderSelector,
            'invoker_exceptions': InvokerSelector,
            'default_access': str,
            'enabled': bool,
            'starts_at': datetime,
            'ends_at': datetime,
            'notes': str
        }

        self.attribute_map = {
            'provider_selector': 'providerSelector',
            'invoker_exceptions': 'invokerExceptions',
            'default_access': 'default_access',
            'enabled': 'enabled',
            'starts_at': 'startsAt',
            'ends_at': 'endsAt',
            'notes': 'notes'
        }

        self._provider_selector = provider_selector
        self._invoker_exceptions = invoker_exceptions
        self._default_access = default_access
        self._enabled = enabled
        self._starts_at = starts_at
        self._ends_at = ends_at
        self._notes = notes

    @classmethod
    def from_dict(cls, dikt) -> 'RulePatchRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RulePatchRequest of this RulePatchRequest.  # noqa: E501
        :rtype: RulePatchRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider_selector(self) -> PatchProviderSelector:
        """Gets the provider_selector of this RulePatchRequest.


        :return: The provider_selector of this RulePatchRequest.
        :rtype: PatchProviderSelector
        """
        return self._provider_selector

    @provider_selector.setter
    def provider_selector(self, provider_selector: PatchProviderSelector):
        """Sets the provider_selector of this RulePatchRequest.


        :param provider_selector: The provider_selector of this RulePatchRequest.
        :type provider_selector: PatchProviderSelector
        """

        self._provider_selector = provider_selector

    @property
    def invoker_exceptions(self) -> InvokerSelector:
        """Gets the invoker_exceptions of this RulePatchRequest.


        :return: The invoker_exceptions of this RulePatchRequest.
        :rtype: InvokerSelector
        """
        return self._invoker_exceptions

    @invoker_exceptions.setter
    def invoker_exceptions(self, invoker_exceptions: InvokerSelector):
        """Sets the invoker_exceptions of this RulePatchRequest.


        :param invoker_exceptions: The invoker_exceptions of this RulePatchRequest.
        :type invoker_exceptions: InvokerSelector
        """

        self._invoker_exceptions = invoker_exceptions

    @property
    def default_access(self) -> str:
        """Gets the default_access of this RulePatchRequest.


        :return: The default_access of this RulePatchRequest.
        :rtype: str
        """
        return self._default_access

    @default_access.setter
    def default_access(self, default_access: str):
        """Sets the default_access of this RulePatchRequest.


        :param default_access: The default_access of this RulePatchRequest.
        :type default_access: str
        """
        allowed_values = ["ALLOW", "DENY"]  # noqa: E501
        if default_access not in allowed_values:
            raise ValueError(
                "Invalid value for `default_access` ({0}), must be one of {1}"
                .format(default_access, allowed_values)
            )

        self._default_access = default_access

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this RulePatchRequest.


        :return: The enabled of this RulePatchRequest.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this RulePatchRequest.


        :param enabled: The enabled of this RulePatchRequest.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def starts_at(self) -> datetime:
        """Gets the starts_at of this RulePatchRequest.


        :return: The starts_at of this RulePatchRequest.
        :rtype: datetime
        """
        return self._starts_at

    @starts_at.setter
    def starts_at(self, starts_at: datetime):
        """Sets the starts_at of this RulePatchRequest.


        :param starts_at: The starts_at of this RulePatchRequest.
        :type starts_at: datetime
        """

        self._starts_at = starts_at

    @property
    def ends_at(self) -> datetime:
        """Gets the ends_at of this RulePatchRequest.


        :return: The ends_at of this RulePatchRequest.
        :rtype: datetime
        """
        return self._ends_at

    @ends_at.setter
    def ends_at(self, ends_at: datetime):
        """Sets the ends_at of this RulePatchRequest.


        :param ends_at: The ends_at of this RulePatchRequest.
        :type ends_at: datetime
        """

        self._ends_at = ends_at

    @property
    def notes(self) -> str:
        """Gets the notes of this RulePatchRequest.


        :return: The notes of this RulePatchRequest.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes: str):
        """Sets the notes of this RulePatchRequest.


        :param notes: The notes of this RulePatchRequest.
        :type notes: str
        """

        self._notes = notes
