from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from visibility_control.models.base_model import Model
from visibility_control.models.invoker_selector import InvokerSelector
from visibility_control.models.provider_selector import ProviderSelector
from visibility_control import util

from visibility_control.models.invoker_selector import InvokerSelector  # noqa: E501
from visibility_control.models.provider_selector import ProviderSelector  # noqa: E501

class Rule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rule_id=None, provider_selector=None, invoker_exceptions=None, default_access=None, enabled=True, starts_at=None, ends_at=None, notes=None, updated_at=None, updated_by=None):  # noqa: E501
        """Rule - a model defined in OpenAPI

        :param rule_id: The rule_id of this Rule.  # noqa: E501
        :type rule_id: str
        :param provider_selector: The provider_selector of this Rule.  # noqa: E501
        :type provider_selector: ProviderSelector
        :param invoker_exceptions: The invoker_exceptions of this Rule.  # noqa: E501
        :type invoker_exceptions: InvokerSelector
        :param default_access: The default_access of this Rule.  # noqa: E501
        :type default_access: str
        :param enabled: The enabled of this Rule.  # noqa: E501
        :type enabled: bool
        :param starts_at: The starts_at of this Rule.  # noqa: E501
        :type starts_at: datetime
        :param ends_at: The ends_at of this Rule.  # noqa: E501
        :type ends_at: datetime
        :param notes: The notes of this Rule.  # noqa: E501
        :type notes: str
        :param updated_at: The updated_at of this Rule.  # noqa: E501
        :type updated_at: datetime
        :param updated_by: The updated_by of this Rule.  # noqa: E501
        :type updated_by: str
        """
        self.openapi_types = {
            'rule_id': str,
            'provider_selector': ProviderSelector,
            'invoker_exceptions': InvokerSelector,
            'default_access': str,
            'enabled': bool,
            'starts_at': datetime,
            'ends_at': datetime,
            'notes': str,
            'updated_at': datetime,
            'updated_by': str
        }

        self.attribute_map = {
            'rule_id': 'ruleId',
            'provider_selector': 'providerSelector',
            'invoker_exceptions': 'invokerExceptions',
            'default_access': 'default_access',
            'enabled': 'enabled',
            'starts_at': 'startsAt',
            'ends_at': 'endsAt',
            'notes': 'notes',
            'updated_at': 'updatedAt',
            'updated_by': 'updatedBy'
        }

        self._rule_id = rule_id
        self._provider_selector = provider_selector
        self._invoker_exceptions = invoker_exceptions
        self._default_access = default_access
        self._enabled = enabled
        self._starts_at = starts_at
        self._ends_at = ends_at
        self._notes = notes
        self._updated_at = updated_at
        self._updated_by = updated_by

    @classmethod
    def from_dict(cls, dikt) -> 'Rule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Rule of this Rule.  # noqa: E501
        :rtype: Rule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rule_id(self) -> str:
        """Gets the rule_id of this Rule.


        :return: The rule_id of this Rule.
        :rtype: str
        """
        return self._rule_id

    @rule_id.setter
    def rule_id(self, rule_id: str):
        """Sets the rule_id of this Rule.


        :param rule_id: The rule_id of this Rule.
        :type rule_id: str
        """
        if rule_id is None:
            raise ValueError("Invalid value for `rule_id`, must not be `None`")  # noqa: E501

        self._rule_id = rule_id

    @property
    def provider_selector(self) -> ProviderSelector:
        """Gets the provider_selector of this Rule.


        :return: The provider_selector of this Rule.
        :rtype: ProviderSelector
        """
        return self._provider_selector

    @provider_selector.setter
    def provider_selector(self, provider_selector: ProviderSelector):
        """Sets the provider_selector of this Rule.


        :param provider_selector: The provider_selector of this Rule.
        :type provider_selector: ProviderSelector
        """
        if provider_selector is None:
            raise ValueError("Invalid value for `provider_selector`, must not be `None`")  # noqa: E501

        self._provider_selector = provider_selector

    @property
    def invoker_exceptions(self) -> InvokerSelector:
        """Gets the invoker_exceptions of this Rule.


        :return: The invoker_exceptions of this Rule.
        :rtype: InvokerSelector
        """
        return self._invoker_exceptions

    @invoker_exceptions.setter
    def invoker_exceptions(self, invoker_exceptions: InvokerSelector):
        """Sets the invoker_exceptions of this Rule.


        :param invoker_exceptions: The invoker_exceptions of this Rule.
        :type invoker_exceptions: InvokerSelector
        """

        self._invoker_exceptions = invoker_exceptions

    @property
    def default_access(self) -> str:
        """Gets the default_access of this Rule.


        :return: The default_access of this Rule.
        :rtype: str
        """
        return self._default_access

    @default_access.setter
    def default_access(self, default_access: str):
        """Sets the default_access of this Rule.


        :param default_access: The default_access of this Rule.
        :type default_access: str
        """
        allowed_values = ["ALLOW", "DENY"]  # noqa: E501
        if default_access not in allowed_values:
            raise ValueError(
                "Invalid value for `default_access` ({0}), must be one of {1}"
                .format(default_access, allowed_values)
            )

        self._default_access = default_access

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this Rule.


        :return: The enabled of this Rule.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this Rule.


        :param enabled: The enabled of this Rule.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def starts_at(self) -> datetime:
        """Gets the starts_at of this Rule.


        :return: The starts_at of this Rule.
        :rtype: datetime
        """
        return self._starts_at

    @starts_at.setter
    def starts_at(self, starts_at: datetime):
        """Sets the starts_at of this Rule.


        :param starts_at: The starts_at of this Rule.
        :type starts_at: datetime
        """

        self._starts_at = starts_at

    @property
    def ends_at(self) -> datetime:
        """Gets the ends_at of this Rule.


        :return: The ends_at of this Rule.
        :rtype: datetime
        """
        return self._ends_at

    @ends_at.setter
    def ends_at(self, ends_at: datetime):
        """Sets the ends_at of this Rule.


        :param ends_at: The ends_at of this Rule.
        :type ends_at: datetime
        """

        self._ends_at = ends_at

    @property
    def notes(self) -> str:
        """Gets the notes of this Rule.


        :return: The notes of this Rule.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes: str):
        """Sets the notes of this Rule.


        :param notes: The notes of this Rule.
        :type notes: str
        """

        self._notes = notes

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Rule.


        :return: The updated_at of this Rule.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Rule.


        :param updated_at: The updated_at of this Rule.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def updated_by(self) -> str:
        """Gets the updated_by of this Rule.


        :return: The updated_by of this Rule.
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by: str):
        """Sets the updated_by of this Rule.


        :param updated_by: The updated_by of this Rule.
        :type updated_by: str
        """

        self._updated_by = updated_by
