from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api import util
from api.models.base_model import Model


class ErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, details=None):  # noqa: E501
        """ErrorResponse - a model defined in OpenAPI

        :param message: The message of this ErrorResponse.  # noqa: E501
        :type message: str
        :param details: The details of this ErrorResponse.  # noqa: E501
        :type details: str
        """
        self.openapi_types = {
            'message': str,
            'details': str
        }

        self.attribute_map = {
            'message': 'message',
            'details': 'details'
        }

        self._message = message
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ErrorResponse.


        :return: The message of this ErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorResponse.


        :param message: The message of this ErrorResponse.
        :type message: str
        """

        self._message = message

    @property
    def details(self) -> str:
        """Gets the details of this ErrorResponse.


        :return: The details of this ErrorResponse.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details: str):
        """Sets the details of this ErrorResponse.


        :param details: The details of this ErrorResponse.
        :type details: str
        """

        self._details = details
