from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api import util
from api.models.base_model import Model


class NotificationMethod(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """NotificationMethod - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationMethod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationMethod of this NotificationMethod.  # noqa: E501
        :rtype: NotificationMethod
        """
        return util.deserialize_model(dikt, cls)
