from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from api import util
from api.models.api_invoker_enrolment_details import \
    APIInvokerEnrolmentDetails  # noqa: E501
from api.models.base_model import Model


class PaginatedResponseInvoker(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, long=None, total_pages=None, sort_order=None, invokers=None):  # noqa: E501
        """PaginatedResponseInvoker - a model defined in OpenAPI

        :param total: The total of this PaginatedResponseInvoker.  # noqa: E501
        :type total: int
        :param long: The long of this PaginatedResponseInvoker.  # noqa: E501
        :type long: int
        :param total_pages: The total_pages of this PaginatedResponseInvoker.  # noqa: E501
        :type total_pages: int
        :param sort_order: The sort_order of this PaginatedResponseInvoker.  # noqa: E501
        :type sort_order: str
        :param invokers: The invokers of this PaginatedResponseInvoker.  # noqa: E501
        :type invokers: List[APIInvokerEnrolmentDetails]
        """
        self.openapi_types = {
            'total': int,
            'long': int,
            'total_pages': int,
            'sort_order': str,
            'invokers': List[APIInvokerEnrolmentDetails]
        }

        self.attribute_map = {
            'total': 'total',
            'long': 'long',
            'total_pages': 'totalPages',
            'sort_order': 'sort_order',
            'invokers': 'invokers'
        }

        self._total = total
        self._long = long
        self._total_pages = total_pages
        self._sort_order = sort_order
        self._invokers = invokers

    @classmethod
    def from_dict(cls, dikt) -> 'PaginatedResponseInvoker':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginatedResponseInvoker of this PaginatedResponseInvoker.  # noqa: E501
        :rtype: PaginatedResponseInvoker
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this PaginatedResponseInvoker.

        Total number of resources in CAPIF.  # noqa: E501

        :return: The total of this PaginatedResponseInvoker.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this PaginatedResponseInvoker.

        Total number of resources in CAPIF.  # noqa: E501

        :param total: The total of this PaginatedResponseInvoker.
        :type total: int
        """

        self._total = total

    @property
    def long(self) -> int:
        """Gets the long of this PaginatedResponseInvoker.

        Total number of resources that match the given parameters  # noqa: E501

        :return: The long of this PaginatedResponseInvoker.
        :rtype: int
        """
        return self._long

    @long.setter
    def long(self, long: int):
        """Sets the long of this PaginatedResponseInvoker.

        Total number of resources that match the given parameters  # noqa: E501

        :param long: The long of this PaginatedResponseInvoker.
        :type long: int
        """

        self._long = long

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this PaginatedResponseInvoker.

        Total number of pages given page size.  # noqa: E501

        :return: The total_pages of this PaginatedResponseInvoker.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this PaginatedResponseInvoker.

        Total number of pages given page size.  # noqa: E501

        :param total_pages: The total_pages of this PaginatedResponseInvoker.
        :type total_pages: int
        """

        self._total_pages = total_pages

    @property
    def sort_order(self) -> str:
        """Gets the sort_order of this PaginatedResponseInvoker.

        Sorting by creation date of the resources (ascending or descending).  # noqa: E501

        :return: The sort_order of this PaginatedResponseInvoker.
        :rtype: str
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: str):
        """Sets the sort_order of this PaginatedResponseInvoker.

        Sorting by creation date of the resources (ascending or descending).  # noqa: E501

        :param sort_order: The sort_order of this PaginatedResponseInvoker.
        :type sort_order: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if sort_order not in allowed_values:
            raise ValueError(
                "Invalid value for `sort_order` ({0}), must be one of {1}"
                .format(sort_order, allowed_values)
            )

        self._sort_order = sort_order

    @property
    def invokers(self) -> List[APIInvokerEnrolmentDetails]:
        """Gets the invokers of this PaginatedResponseInvoker.

        CAPIF invokers list  # noqa: E501

        :return: The invokers of this PaginatedResponseInvoker.
        :rtype: List[APIInvokerEnrolmentDetails]
        """
        return self._invokers

    @invokers.setter
    def invokers(self, invokers: List[APIInvokerEnrolmentDetails]):
        """Sets the invokers of this PaginatedResponseInvoker.

        CAPIF invokers list  # noqa: E501

        :param invokers: The invokers of this PaginatedResponseInvoker.
        :type invokers: List[APIInvokerEnrolmentDetails]
        """

        self._invokers = invokers
