map "$endpoint:$method:$role" $discover_service_mtls_policy {
    default DENY;
    # Discover policies that use mTLS for authentication
    ~^discover_service_exact:GET:(invoker|ccf|superadmin)$ ALLOW;
}

