map "$endpoint:$method:$role" $events_service_mtls_policy {
    default DENY;
    #Publish policies that use mTLS for authentication
    ~^events_tree:(POST|DELETE|PUT|PATCH):(amf|apf|aef|invoker|superadmin)$ ALLOW;
}

