map "$endpoint:$method:$role" $invoker_mtls_policy {
    default DENY;
    # Invoker policies that use mTLS for authentication
    ~^invoker_onboarding_tree:(PUT|DELETE|PATCH):superadmin$ ALLOW;
    ~^invoker_onboarding_tree:(PUT|DELETE|PATCH):invoker$ ALLOW;
}

