map "$endpoint:$method:$role" $provider_mtls_policy {
    default DENY;
    #Provider policies that use mTLS for authentication
    ~^provider_registrations_tree:(PUT|DELETE|PATCH):superadmin$     ALLOW;
    ~^provider_registrations_tree:(PUT|DELETE|PATCH):amf$            ALLOW;
}

