map "$endpoint:$method:$role" $publish_service_mtls_policy {
    default DENY;
    #Publish policies that use mTLS for authentication
    ~^published_apis_tree:(GET|POST|PUT|DELETE|PATCH):(apf|superadmin|ccf)$ ALLOW;
}

