map "$endpoint:$method:$role" $security_service_mtls_policy {
    default DENY;
    # Security policies that use mTLS for authentication
    security_trusted_invokers_exact:DELETE:aef ALLOW;
    security_trusted_invokers_exact:PUT:invoker ALLOW;
    security_trusted_invokers_exact:GET:aef ALLOW;
    security_update:POST:invoker ALLOW;
    security_delete:POST:aef ALLOW;
    security_token:POST:invoker ALLOW;

    ~^.*:.*:superadmin$ ALLOW;
    
}

