import re  # noqa: E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model import Model
from openapi_server.models.open_api_details import OpenAPIDetails  # noqa: E501


class OpenDiscoveryResp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, disc_apis=None, supp_feat=None):  # noqa: E501
        """OpenDiscoveryResp - a model defined in OpenAPI

        :param disc_apis: The disc_apis of this OpenDiscoveryResp.  # noqa: E501
        :type disc_apis: List[OpenAPIDetails]
        :param supp_feat: The supp_feat of this OpenDiscoveryResp.  # noqa: E501
        :type supp_feat: str
        """
        self.openapi_types = {
            'disc_apis': List[OpenAPIDetails],
            'supp_feat': str
        }

        self.attribute_map = {
            'disc_apis': 'discApis',
            'supp_feat': 'suppFeat'
        }

        self._disc_apis = disc_apis
        self._supp_feat = supp_feat

    @classmethod
    def from_dict(cls, dikt) -> 'OpenDiscoveryResp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpenDiscoveryResp of this OpenDiscoveryResp.  # noqa: E501
        :rtype: OpenDiscoveryResp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disc_apis(self) -> List[OpenAPIDetails]:
        """Gets the disc_apis of this OpenDiscoveryResp.


        :return: The disc_apis of this OpenDiscoveryResp.
        :rtype: List[OpenAPIDetails]
        """
        return self._disc_apis

    @disc_apis.setter
    def disc_apis(self, disc_apis: List[OpenAPIDetails]):
        """Sets the disc_apis of this OpenDiscoveryResp.


        :param disc_apis: The disc_apis of this OpenDiscoveryResp.
        :type disc_apis: List[OpenAPIDetails]
        """
        if disc_apis is None:
            raise ValueError("Invalid value for `disc_apis`, must not be `None`")  # noqa: E501
        if disc_apis is not None and len(disc_apis) < 0:
            raise ValueError("Invalid value for `disc_apis`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._disc_apis = disc_apis

    @property
    def supp_feat(self) -> str:
        """Gets the supp_feat of this OpenDiscoveryResp.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supp_feat of this OpenDiscoveryResp.
        :rtype: str
        """
        return self._supp_feat

    @supp_feat.setter
    def supp_feat(self, supp_feat: str):
        """Sets the supp_feat of this OpenDiscoveryResp.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supp_feat: The supp_feat of this OpenDiscoveryResp.
        :type supp_feat: str
        """
        if supp_feat is not None and not re.search(r'^[A-Fa-f0-9]*$', supp_feat):  # noqa: E501
            raise ValueError(r"Invalid value for `supp_feat`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supp_feat = supp_feat
