from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from openapi_server import util
from openapi_server.models.aef_location import AefLocation  # noqa: E501
from openapi_server.models.base_model import Model
from openapi_server.models.data_format import DataFormat  # noqa: E501
from openapi_server.models.protocol import Protocol  # noqa: E501
from openapi_server.models.service_kpis import ServiceKpis  # noqa: E501
from openapi_server.models.version import Version  # noqa: E501


class OpenAefProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, aef_id=None, versions=None, protocol=None, data_format=None, aef_location=None, service_kpis=None):  # noqa: E501
        """OpenAefProfile - a model defined in OpenAPI

        :param aef_id: The aef_id of this OpenAefProfile.  # noqa: E501
        :type aef_id: str
        :param versions: The versions of this OpenAefProfile.  # noqa: E501
        :type versions: List[Version]
        :param protocol: The protocol of this OpenAefProfile.  # noqa: E501
        :type protocol: Protocol
        :param data_format: The data_format of this OpenAefProfile.  # noqa: E501
        :type data_format: DataFormat
        :param aef_location: The aef_location of this OpenAefProfile.  # noqa: E501
        :type aef_location: AefLocation
        :param service_kpis: The service_kpis of this OpenAefProfile.  # noqa: E501
        :type service_kpis: ServiceKpis
        """
        self.openapi_types = {
            'aef_id': str,
            'versions': List[Version],
            'protocol': Protocol,
            'data_format': DataFormat,
            'aef_location': AefLocation,
            'service_kpis': ServiceKpis
        }

        self.attribute_map = {
            'aef_id': 'aefId',
            'versions': 'versions',
            'protocol': 'protocol',
            'data_format': 'dataFormat',
            'aef_location': 'aefLocation',
            'service_kpis': 'serviceKpis'
        }

        self._aef_id = aef_id
        self._versions = versions
        self._protocol = protocol
        self._data_format = data_format
        self._aef_location = aef_location
        self._service_kpis = service_kpis

    @classmethod
    def from_dict(cls, dikt) -> 'OpenAefProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpenAefProfile of this OpenAefProfile.  # noqa: E501
        :rtype: OpenAefProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aef_id(self) -> str:
        """Gets the aef_id of this OpenAefProfile.


        :return: The aef_id of this OpenAefProfile.
        :rtype: str
        """
        return self._aef_id

    @aef_id.setter
    def aef_id(self, aef_id: str):
        """Sets the aef_id of this OpenAefProfile.


        :param aef_id: The aef_id of this OpenAefProfile.
        :type aef_id: str
        """

        self._aef_id = aef_id

    @property
    def versions(self) -> List[Version]:
        """Gets the versions of this OpenAefProfile.


        :return: The versions of this OpenAefProfile.
        :rtype: List[Version]
        """
        return self._versions

    @versions.setter
    def versions(self, versions: List[Version]):
        """Sets the versions of this OpenAefProfile.


        :param versions: The versions of this OpenAefProfile.
        :type versions: List[Version]
        """
        if versions is not None and len(versions) < 1:
            raise ValueError("Invalid value for `versions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._versions = versions

    @property
    def protocol(self) -> Protocol:
        """Gets the protocol of this OpenAefProfile.


        :return: The protocol of this OpenAefProfile.
        :rtype: Protocol
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: Protocol):
        """Sets the protocol of this OpenAefProfile.


        :param protocol: The protocol of this OpenAefProfile.
        :type protocol: Protocol
        """

        self._protocol = protocol

    @property
    def data_format(self) -> DataFormat:
        """Gets the data_format of this OpenAefProfile.


        :return: The data_format of this OpenAefProfile.
        :rtype: DataFormat
        """
        return self._data_format

    @data_format.setter
    def data_format(self, data_format: DataFormat):
        """Sets the data_format of this OpenAefProfile.


        :param data_format: The data_format of this OpenAefProfile.
        :type data_format: DataFormat
        """

        self._data_format = data_format

    @property
    def aef_location(self) -> AefLocation:
        """Gets the aef_location of this OpenAefProfile.


        :return: The aef_location of this OpenAefProfile.
        :rtype: AefLocation
        """
        return self._aef_location

    @aef_location.setter
    def aef_location(self, aef_location: AefLocation):
        """Sets the aef_location of this OpenAefProfile.


        :param aef_location: The aef_location of this OpenAefProfile.
        :type aef_location: AefLocation
        """

        self._aef_location = aef_location

    @property
    def service_kpis(self) -> ServiceKpis:
        """Gets the service_kpis of this OpenAefProfile.


        :return: The service_kpis of this OpenAefProfile.
        :rtype: ServiceKpis
        """
        return self._service_kpis

    @service_kpis.setter
    def service_kpis(self, service_kpis: ServiceKpis):
        """Sets the service_kpis of this OpenAefProfile.


        :param service_kpis: The service_kpis of this OpenAefProfile.
        :type service_kpis: ServiceKpis
        """

        self._service_kpis = service_kpis
