import re  # noqa: E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from openapi_server import util
from openapi_server.models.api_status import ApiStatus  # noqa: E501
from openapi_server.models.base_model import Model
from openapi_server.models.open_aef_profile import OpenAefProfile  # noqa: E501


class OpenAPIDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_name=None, api_id=None, api_status=None, description=None, service_api_category=None, api_supp_feats=None, api_prov_name=None, aef_profiles=None):  # noqa: E501
        """OpenAPIDetails - a model defined in OpenAPI

        :param api_name: The api_name of this OpenAPIDetails.  # noqa: E501
        :type api_name: str
        :param api_id: The api_id of this OpenAPIDetails.  # noqa: E501
        :type api_id: str
        :param api_status: The api_status of this OpenAPIDetails.  # noqa: E501
        :type api_status: ApiStatus
        :param description: The description of this OpenAPIDetails.  # noqa: E501
        :type description: str
        :param service_api_category: The service_api_category of this OpenAPIDetails.  # noqa: E501
        :type service_api_category: str
        :param api_supp_feats: The api_supp_feats of this OpenAPIDetails.  # noqa: E501
        :type api_supp_feats: str
        :param api_prov_name: The api_prov_name of this OpenAPIDetails.  # noqa: E501
        :type api_prov_name: str
        :param aef_profiles: The aef_profiles of this OpenAPIDetails.  # noqa: E501
        :type aef_profiles: List[OpenAefProfile]
        """
        self.openapi_types = {
            'api_name': str,
            'api_id': str,
            'api_status': ApiStatus,
            'description': str,
            'service_api_category': str,
            'api_supp_feats': str,
            'api_prov_name': str,
            'aef_profiles': List[OpenAefProfile]
        }

        self.attribute_map = {
            'api_name': 'apiName',
            'api_id': 'apiId',
            'api_status': 'apiStatus',
            'description': 'description',
            'service_api_category': 'serviceAPICategory',
            'api_supp_feats': 'apiSuppFeats',
            'api_prov_name': 'apiProvName',
            'aef_profiles': 'aefProfiles'
        }

        self._api_name = api_name
        self._api_id = api_id
        self._api_status = api_status
        self._description = description
        self._service_api_category = service_api_category
        self._api_supp_feats = api_supp_feats
        self._api_prov_name = api_prov_name
        self._aef_profiles = aef_profiles

    @classmethod
    def from_dict(cls, dikt) -> 'OpenAPIDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpenAPIDetails of this OpenAPIDetails.  # noqa: E501
        :rtype: OpenAPIDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_name(self) -> str:
        """Gets the api_name of this OpenAPIDetails.


        :return: The api_name of this OpenAPIDetails.
        :rtype: str
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name: str):
        """Sets the api_name of this OpenAPIDetails.


        :param api_name: The api_name of this OpenAPIDetails.
        :type api_name: str
        """
        if api_name is None:
            raise ValueError("Invalid value for `api_name`, must not be `None`")  # noqa: E501

        self._api_name = api_name

    @property
    def api_id(self) -> str:
        """Gets the api_id of this OpenAPIDetails.


        :return: The api_id of this OpenAPIDetails.
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id: str):
        """Sets the api_id of this OpenAPIDetails.


        :param api_id: The api_id of this OpenAPIDetails.
        :type api_id: str
        """

        self._api_id = api_id

    @property
    def api_status(self) -> ApiStatus:
        """Gets the api_status of this OpenAPIDetails.


        :return: The api_status of this OpenAPIDetails.
        :rtype: ApiStatus
        """
        return self._api_status

    @api_status.setter
    def api_status(self, api_status: ApiStatus):
        """Sets the api_status of this OpenAPIDetails.


        :param api_status: The api_status of this OpenAPIDetails.
        :type api_status: ApiStatus
        """

        self._api_status = api_status

    @property
    def description(self) -> str:
        """Gets the description of this OpenAPIDetails.


        :return: The description of this OpenAPIDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OpenAPIDetails.


        :param description: The description of this OpenAPIDetails.
        :type description: str
        """

        self._description = description

    @property
    def service_api_category(self) -> str:
        """Gets the service_api_category of this OpenAPIDetails.


        :return: The service_api_category of this OpenAPIDetails.
        :rtype: str
        """
        return self._service_api_category

    @service_api_category.setter
    def service_api_category(self, service_api_category: str):
        """Sets the service_api_category of this OpenAPIDetails.


        :param service_api_category: The service_api_category of this OpenAPIDetails.
        :type service_api_category: str
        """

        self._service_api_category = service_api_category

    @property
    def api_supp_feats(self) -> str:
        """Gets the api_supp_feats of this OpenAPIDetails.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The api_supp_feats of this OpenAPIDetails.
        :rtype: str
        """
        return self._api_supp_feats

    @api_supp_feats.setter
    def api_supp_feats(self, api_supp_feats: str):
        """Sets the api_supp_feats of this OpenAPIDetails.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param api_supp_feats: The api_supp_feats of this OpenAPIDetails.
        :type api_supp_feats: str
        """
        if api_supp_feats is not None and not re.search(r'^[A-Fa-f0-9]*$', api_supp_feats):  # noqa: E501
            raise ValueError(r"Invalid value for `api_supp_feats`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._api_supp_feats = api_supp_feats

    @property
    def api_prov_name(self) -> str:
        """Gets the api_prov_name of this OpenAPIDetails.


        :return: The api_prov_name of this OpenAPIDetails.
        :rtype: str
        """
        return self._api_prov_name

    @api_prov_name.setter
    def api_prov_name(self, api_prov_name: str):
        """Sets the api_prov_name of this OpenAPIDetails.


        :param api_prov_name: The api_prov_name of this OpenAPIDetails.
        :type api_prov_name: str
        """

        self._api_prov_name = api_prov_name

    @property
    def aef_profiles(self) -> List[OpenAefProfile]:
        """Gets the aef_profiles of this OpenAPIDetails.


        :return: The aef_profiles of this OpenAPIDetails.
        :rtype: List[OpenAefProfile]
        """
        return self._aef_profiles

    @aef_profiles.setter
    def aef_profiles(self, aef_profiles: List[OpenAefProfile]):
        """Sets the aef_profiles of this OpenAPIDetails.


        :param aef_profiles: The aef_profiles of this OpenAPIDetails.
        :type aef_profiles: List[OpenAefProfile]
        """
        if aef_profiles is not None and len(aef_profiles) < 1:
            raise ValueError("Invalid value for `aef_profiles`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._aef_profiles = aef_profiles
