from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_security import util
from capif_security.models.base_model import Model


class QueryParameter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, value=None):  # noqa: E501
        """QueryParameter - a model defined in OpenAPI

        :param name: The name of this QueryParameter.  # noqa: E501
        :type name: str
        :param value: The value of this QueryParameter.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }

        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'QueryParameter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryParameter of this QueryParameter.  # noqa: E501
        :rtype: QueryParameter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this QueryParameter.


        :return: The name of this QueryParameter.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this QueryParameter.


        :param name: The name of this QueryParameter.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self) -> str:
        """Gets the value of this QueryParameter.


        :return: The value of this QueryParameter.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this QueryParameter.


        :param value: The value of this QueryParameter.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
