from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from capif_security import util
from capif_security.models.base_model import Model
from capif_security.models.query_parameter import QueryParameter  # noqa: E501


class QueryParamCombination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _query_params=None):  # noqa: E501
        """QueryParamCombination - a model defined in OpenAPI

        :param _query_params: The _query_params of this QueryParamCombination.  # noqa: E501
        :type _query_params: List[QueryParameter]
        """
        self.openapi_types = {
            '_query_params': List[QueryParameter]
        }

        self.attribute_map = {
            '_query_params': 'queryParams'
        }

        self.__query_params = _query_params

    @classmethod
    def from_dict(cls, dikt) -> 'QueryParamCombination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryParamCombination of this QueryParamCombination.  # noqa: E501
        :rtype: QueryParamCombination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _query_params(self) -> List[QueryParameter]:
        """Gets the _query_params of this QueryParamCombination.


        :return: The _query_params of this QueryParamCombination.
        :rtype: List[QueryParameter]
        """
        return self.__query_params

    @_query_params.setter
    def _query_params(self, _query_params: List[QueryParameter]):
        """Sets the _query_params of this QueryParamCombination.


        :param _query_params: The _query_params of this QueryParamCombination.
        :type _query_params: List[QueryParameter]
        """
        if _query_params is None:
            raise ValueError("Invalid value for `_query_params`, must not be `None`")  # noqa: E501
        if _query_params is not None and len(_query_params) < 1:
            raise ValueError("Invalid value for `_query_params`, number of items must be greater than or equal to `1`")  # noqa: E501

        self.__query_params = _query_params
