# -- To enable monitoring in ocf.
# -- enabled the next services:
# -- tempo, fluentbit, grafana, loki, otelcollector and renderer.
# -- prometheus service must be previously installed in kubernetes


