{{- if .Values.enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: mongo-register-express
  labels:
    {{- include "mongo-register-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-register-express.selectorLabels" . | nindent 4 }}
{{- end }}