from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from published_apis import util
from published_apis.models.base_model import Model
from published_apis.models.snssai import Snssai  # noqa: E501


class NetSliceId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, snssai=None, nsi_id=None, ensi=None):  # noqa: E501
        """NetSliceId - a model defined in OpenAPI

        :param snssai: The snssai of this NetSliceId.  # noqa: E501
        :type snssai: Snssai
        :param nsi_id: The nsi_id of this NetSliceId.  # noqa: E501
        :type nsi_id: str
        :param ensi: The ensi of this NetSliceId.  # noqa: E501
        :type ensi: str
        """
        self.openapi_types = {
            'snssai': Snssai,
            'nsi_id': str,
            'ensi': str
        }

        self.attribute_map = {
            'snssai': 'snssai',
            'nsi_id': 'nsiId',
            'ensi': 'ensi'
        }

        self._snssai = snssai
        self._nsi_id = nsi_id
        self._ensi = ensi

    @classmethod
    def from_dict(cls, dikt) -> 'NetSliceId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NetSliceId of this NetSliceId.  # noqa: E501
        :rtype: NetSliceId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def snssai(self) -> Snssai:
        """Gets the snssai of this NetSliceId.


        :return: The snssai of this NetSliceId.
        :rtype: Snssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai: Snssai):
        """Sets the snssai of this NetSliceId.


        :param snssai: The snssai of this NetSliceId.
        :type snssai: Snssai
        """

        self._snssai = snssai

    @property
    def nsi_id(self) -> str:
        """Gets the nsi_id of this NetSliceId.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :return: The nsi_id of this NetSliceId.
        :rtype: str
        """
        return self._nsi_id

    @nsi_id.setter
    def nsi_id(self, nsi_id: str):
        """Sets the nsi_id of this NetSliceId.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :param nsi_id: The nsi_id of this NetSliceId.
        :type nsi_id: str
        """

        self._nsi_id = nsi_id

    @property
    def ensi(self) -> str:
        """Gets the ensi of this NetSliceId.

        Represents the External Network Slice Information that is used to identify a network slice, as specified in 3GPP TS 33.501.   # noqa: E501

        :return: The ensi of this NetSliceId.
        :rtype: str
        """
        return self._ensi

    @ensi.setter
    def ensi(self, ensi: str):
        """Sets the ensi of this NetSliceId.

        Represents the External Network Slice Information that is used to identify a network slice, as specified in 3GPP TS 33.501.   # noqa: E501

        :param ensi: The ensi of this NetSliceId.
        :type ensi: str
        """

        self._ensi = ensi
