map $uri $service {
    default "";
    ~^/helper(/|$)  helper;
    ~^/api-invoker-management(/|$)  invoker-management;
    ~^/api-provider-management(/|$)  provider-management;
    ~^/service-apis(/|$)  discover-service;
    ~^/open-api-disc(/|$)  open-discover-service;
    ~^/published-apis(/|$)  publish-service;
    ~^/api-invocation-logs(/|$)  logging-service;
    ~^/logs(/|$)  auditing-service;
    ~^/capif-security(/|$)  security-service;
    ~^/capif-events(/|$)  events-service;
    ~^/access-control-policy(/|$)  access-control-policy;
}
