map $ssl_client_s_dn_cn $role {
    default unknown;
    superadmin            superadmin;
    "~^INV[a-zA-Z0-9]+$"    invoker;
    "~^AMF[a-zA-Z0-9]+$"    amf;
    "~^APF[a-zA-Z0-9]+$"    apf;
    "~^AEF[a-zA-Z0-9]+$"    aef;
    "~^CCF[a-zA-Z0-9]+$"    ccf;
}