map "$service:$has_token:$has_cert" $active_policy {
    default DENY;
    # Define policies for each service, based on the presence of a token and/or client certificate
    # The format is: service_name:has_token:has_cert

    # Helper Service
    helper:0:1 $helper_mtls_policy;

    # Api Invoker Management Service
    invoker-management:1:0 $invoker_token_policy;
    invoker-management:0:1 $invoker_mtls_policy;

    # Api Provider Management Service
    provider-management:1:0 $provider_token_policy;
    provider-management:0:1 $provider_mtls_policy;

    # Discover Service
    discover-service:0:1 $discover_service_mtls_policy;

    # Open-Discover Service
    open-discover-service:1:0 $open_discover_token_policy;

    # Published APIs Service
    publish-service:0:1 $publish_service_mtls_policy;

    # Logging Service
    logging-service:0:1 $logging_service_mtls_policy;

    # Auditing Service
    auditing-service:0:1 $auditing_service_mtls_policy;

    # Security Service
    security-service:0:1 $security_service_mtls_policy; 

    # Events Service
    events-service:0:1 $events_service_mtls_policy;

    # Access Control Policy Service
    access-control-policy:0:1 $access_control_policy_mtls_policy;

}
