apiVersion: v1
kind: Service
metadata:
  name: capif-routing-info
  labels:
    {{- include "ocf-routing-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ocf-routing-info.selectorLabels" . | nindent 4 }}
