apiVersion: v1
kind: Service
metadata:
  name: logs
  labels:
    {{- include "ocf-auditing-api-logs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ocf-auditing-api-logs.selectorLabels" . | nindent 4 }}
