map $uri $endpoint {
    default "NO MATCH";

    # Exact matches for endpoints that require specific handling (Must be on top of the regex matches)
    /api-invoker-management/v1/onboardedInvokers invoker_onboarding_exact;
    /api-provider-management/v1/registrations provider_registrations_exact;
    /service-apis/v1/allServiceAPIs discover_service_exact;
    /open-api-disc/v1/service-apis open_discover_exact;

    # Regex matches for endpoints that can be grouped by common patterns
    # Helper related endpoints
    ~^/helper/ helper_base_tree;

    # Invoker management related endpoints
    ~^/api-invoker-management/v1/onboardedInvokers/ invoker_onboarding_tree;

    # Provider management related endpoints
    ~^/api-provider-management/v1/registrations/ provider_registrations_tree;
    
    # Published APIs related endpoints
    ~^/published-apis/v1/ published_apis_tree;

    # Logging related endpoints
    ~^/api-invocation-logs/v1/ logging_tree;
    
    # Auditing related endpoints
    ~^/logs/v1/ auditing_tree;

    # Security related endpoints
    ~^/capif-security/v1/trustedInvokers/.+/update  security_update;
    ~^/capif-security/v1/trustedInvokers/.+/delete  security_delete;
    ~^/capif-security/v1/trustedInvokers/.+  security_trusted_invokers_exact;
    ~^/capif-security/v1/securities/.+/token  security_token;
    ~^/capif-security/v1/  security_tree;

    # Events related endpoints
    ~^/capif-events/v1/  events_tree;

    # Access control policy related endpoints
    ~^/access-control-policy/v1/  acl_tree;
}
